# Generated by Django 5.2.8 on 2025-12-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('model_year', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
