# Generated by Django 5.2.8 on 2025-12-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carbooking_delete_carregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('nearest_showroom', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CarBooking',
        ),
    ]
