# Generated by Django 5.2.8 on 2025-12-17 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carregistration_delete_carbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carregistration',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carregistration',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carregistration',
            name='nearest_showroom',
            field=models.CharField(max_length=100),
        ),
    ]
